// 20220125191608
// /wp-json/menus/v1/menus/brands/

export const FooterBrandModel = {
  term_id: 623,
  name: "Brands",
  slug: "brands",
  term_group: 0,
  term_taxonomy_id: 623,
  taxonomy: "nav_menu",
  description: "",
  parent: 0,
  count: 7,
  filter: "raw",
  items: [
    {
      ID: 56356,
      post_author: "1",
      post_date: "2019-01-12 08:21:50",
      post_date_gmt: "2019-01-12 08:21:50",
      post_content:
        "Are you looking Nike shoes release dates? If you are an absolute sneaker lover, then FastSole is the best place to search for Nike sneaker launch dates and upcoming news of Nike shoes in UK and Europe. Visit fastsole.co.uk to know more Nike release dates and upcoming news of Nike shoes. We have a large collection of Nike Air Max 1, Air Max 90, Air Max 96, Air Max Zeo shoes. Not only these, we have also listed in something different like the Air Force 1 or  Air Footscape. In case, if you might want to try them, that is why we have these too. We bring you all the Nike custom trainers and Casual trainer updates so that you don’t miss a single release. Nike Sneaker Release Dates in UK | Nike Launch Dates in UK",
      post_title: "",
      post_excerpt: "",
      post_status: "publish",
      comment_status: "closed",
      ping_status: "closed",
      post_password: "",
      post_name: "56356",
      to_ping: "",
      pinged: "",
      post_modified: "2019-03-31 09:51:50",
      post_modified_gmt: "2019-03-31 08:51:50",
      post_content_filtered: "",
      post_parent: 0,
      guid: "https://fastsole.co.uk/?p=56356",
      menu_order: 1,
      post_type: "nav_menu_item",
      post_mime_type: "",
      comment_count: "0",
      filter: "raw",
      db_id: 56356,
      menu_item_parent: "0",
      object_id: "54",
      object: "department",
      type: "taxonomy",
      type_label: "Department",
      url: "/sneaker-release-dates/brands/nike/",
      title: "Nike",
      target: "",
      attr_title: "",
      description:
        "Are you looking Nike shoes release dates? If you are an absolute sneaker lover, then FastSole is the best place to search for Nike sneaker launch dates and upcoming news of Nike shoes in UK and Europe. Visit fastsole.co.uk to know more Nike release dates and upcoming news of Nike shoes. We have a large collection of Nike Air Max 1, Air Max 90, Air Max 96, Air Max Zeo shoes. Not only these, we have also listed in something different like the Air Force 1 or  Air Footscape. In case, if you might want to try them, that is why we have these too. We bring you all the Nike custom trainers and Casual trainer updates so that you don’t miss a single release. Nike Sneaker Release Dates in UK | Nike Launch Dates in UK",
      classes: [""],
      xfn: "",
      slug: "nike",
    },
    {
      ID: 56360,
      post_author: "1",
      post_date: "2019-01-12 08:21:50",
      post_date_gmt: "2019-01-12 08:21:50",
      post_content:
        "FastSole is the best place to know release date of adidas or adidas Release Dates in UK shoes and upcoming related news about them. We gather all the information so that you don’t need to look anywhere else. Our collection includes all the latest adidas series including the Ultra Boost, NMD XR1, NMD R1, SPEZIAL and Yeezy trainers. Visit our website to get Adidas Ultra Boost sale related info or any detailed news on Adidas Running Trainers in UK and Europe.",
      post_title: "",
      post_excerpt: "",
      post_status: "publish",
      comment_status: "closed",
      ping_status: "closed",
      post_password: "",
      post_name: "56360",
      to_ping: "",
      pinged: "",
      post_modified: "2019-03-31 09:51:51",
      post_modified_gmt: "2019-03-31 08:51:51",
      post_content_filtered: "",
      post_parent: 0,
      guid: "https://fastsole.co.uk/?p=56360",
      menu_order: 2,
      post_type: "nav_menu_item",
      post_mime_type: "",
      comment_count: "0",
      filter: "raw",
      db_id: 56360,
      menu_item_parent: "0",
      object_id: "50",
      object: "department",
      type: "taxonomy",
      type_label: "Department",
      url: "/sneaker-release-dates/brands/adidas/",
      title: "adidas",
      target: "",
      attr_title: "",
      description:
        "FastSole is the best place to know release date of adidas or adidas Release Dates in UK shoes and upcoming related news about them. We gather all the information so that you don’t need to look anywhere else. Our collection includes all the latest adidas series including the Ultra Boost, NMD XR1, NMD R1, SPEZIAL and Yeezy trainers. Visit our website to get Adidas Ultra Boost sale related info or any detailed news on Adidas Running Trainers in UK and Europe.",
      classes: [""],
      xfn: "",
      slug: "adidas",
    },
    {
      ID: 63780,
      post_author: "1",
      post_date: "2019-03-31 09:51:44",
      post_date_gmt: "2019-03-31 08:51:44",
      post_content:
        "Over the year Puma has made a strong name in the sneaker industry. In FastSole, we know that your ultimate choice relies on Puma brand and thus provides all Puma Sneaker Release Date. The latest deliveries from the German brand are the Shantell Martin, Platform, Basket lines of shoes that rocked the universe. Also, the longtime famous line RS has returned with the RS-350. We have seen collaboration with pop star Rihanna and Big Sean. All these in hand, Puma has established itself as a recognisable fashion trend. So count on us for your selected pair because Fastsole is the best place, where you will collect Puma sneaker release and news update with confirmed stock list, price, size and more. Puma Shoes Release Dates in UK",
      post_title: "",
      post_excerpt: "",
      post_status: "publish",
      comment_status: "closed",
      ping_status: "closed",
      post_password: "",
      post_name: "63780",
      to_ping: "",
      pinged: "",
      post_modified: "2019-03-31 09:51:51",
      post_modified_gmt: "2019-03-31 08:51:51",
      post_content_filtered: "",
      post_parent: 0,
      guid: "https://fastsole.co.uk/?p=63780",
      menu_order: 3,
      post_type: "nav_menu_item",
      post_mime_type: "",
      comment_count: "0",
      filter: "raw",
      db_id: 63780,
      menu_item_parent: "0",
      object_id: "74",
      object: "department",
      type: "taxonomy",
      type_label: "Department",
      url: "/sneaker-release-dates/brands/puma/",
      title: "Puma",
      target: "",
      attr_title: "",
      description:
        "Over the year Puma has made a strong name in the sneaker industry. In FastSole, we know that your ultimate choice relies on Puma brand and thus provides all Puma Sneaker Release Date. The latest deliveries from the German brand are the Shantell Martin, Platform, Basket lines of shoes that rocked the universe. Also, the longtime famous line RS has returned with the RS-350. We have seen collaboration with pop star Rihanna and Big Sean. All these in hand, Puma has established itself as a recognisable fashion trend. So count on us for your selected pair because Fastsole is the best place, where you will collect Puma sneaker release and news update with confirmed stock list, price, size and more. Puma Shoes Release Dates in UK",
      classes: [""],
      xfn: "",
      slug: "puma",
    },
    {
      ID: 63778,
      post_author: "1",
      post_date: "2019-03-31 09:51:44",
      post_date_gmt: "2019-03-31 08:51:44",
      post_content: " ",
      post_title: "",
      post_excerpt: "",
      post_status: "publish",
      comment_status: "closed",
      ping_status: "closed",
      post_password: "",
      post_name: "63778",
      to_ping: "",
      pinged: "",
      post_modified: "2019-03-31 09:51:51",
      post_modified_gmt: "2019-03-31 08:51:51",
      post_content_filtered: "",
      post_parent: 0,
      guid: "https://fastsole.co.uk/?p=63778",
      menu_order: 4,
      post_type: "nav_menu_item",
      post_mime_type: "",
      comment_count: "0",
      filter: "raw",
      db_id: 63778,
      menu_item_parent: "0",
      object_id: "311",
      object: "department",
      type: "taxonomy",
      type_label: "Department",
      url: "/sneaker-release-dates/brands/converse/",
      title: "Converse",
      target: "",
      attr_title: "",
      description: "",
      classes: [""],
      xfn: "",
      slug: "converse",
    },
    {
      ID: 63779,
      post_author: "1",
      post_date: "2019-03-31 09:51:44",
      post_date_gmt: "2019-03-31 08:51:44",
      post_content:
        "FastSole is the one stop for all the most desired New Balance kicks. If you are a New Balance fan then you are in the right place because FastSole helps you cop awesome kicks with all the detailed news and updates on the New Balance runners in the UK and European stockists. Our collection includes all the latest New Balance trainers to make your sneaker game more lit.",
      post_title: "",
      post_excerpt: "",
      post_status: "publish",
      comment_status: "closed",
      ping_status: "closed",
      post_password: "",
      post_name: "63779",
      to_ping: "",
      pinged: "",
      post_modified: "2019-03-31 09:51:51",
      post_modified_gmt: "2019-03-31 08:51:51",
      post_content_filtered: "",
      post_parent: 0,
      guid: "https://fastsole.co.uk/?p=63779",
      menu_order: 5,
      post_type: "nav_menu_item",
      post_mime_type: "",
      comment_count: "0",
      filter: "raw",
      db_id: 63779,
      menu_item_parent: "0",
      object_id: "158",
      object: "department",
      type: "taxonomy",
      type_label: "Department",
      url: "/sneaker-release-dates/brands/new-balance/",
      title: "New Balance",
      target: "",
      attr_title: "",
      description:
        "FastSole is the one stop for all the most desired New Balance kicks. If you are a New Balance fan then you are in the right place because FastSole helps you cop awesome kicks with all the detailed news and updates on the New Balance runners in the UK and European stockists. Our collection includes all the latest New Balance trainers to make your sneaker game more lit.",
      classes: [""],
      xfn: "",
      slug: "new-balance",
    },
    {
      ID: 63777,
      post_author: "1",
      post_date: "2019-03-31 09:51:44",
      post_date_gmt: "2019-03-31 08:51:44",
      post_content:
        "FastSole brings you all the most desired ASICS kicks. If you are an ASICS fan then you are in the right place because FastSole helps you cop awesome kicks with all the detailed news on the ASICS runners in the UK and European stockists. Our collection includes all the latest ASICS trainers to make your sneaker game more lit.",
      post_title: "",
      post_excerpt: "",
      post_status: "publish",
      comment_status: "closed",
      ping_status: "closed",
      post_password: "",
      post_name: "63777",
      to_ping: "",
      pinged: "",
      post_modified: "2019-03-31 09:51:51",
      post_modified_gmt: "2019-03-31 08:51:51",
      post_content_filtered: "",
      post_parent: 0,
      guid: "https://fastsole.co.uk/?p=63777",
      menu_order: 6,
      post_type: "nav_menu_item",
      post_mime_type: "",
      comment_count: "0",
      filter: "raw",
      db_id: 63777,
      menu_item_parent: "0",
      object_id: "70",
      object: "department",
      type: "taxonomy",
      type_label: "Department",
      url: "/sneaker-release-dates/brands/asics/",
      title: "ASICS",
      target: "",
      attr_title: "",
      description:
        "FastSole brings you all the most desired ASICS kicks. If you are an ASICS fan then you are in the right place because FastSole helps you cop awesome kicks with all the detailed news on the ASICS runners in the UK and European stockists. Our collection includes all the latest ASICS trainers to make your sneaker game more lit.",
      classes: [""],
      xfn: "",
      slug: "asics",
    },
    {
      ID: 63781,
      post_author: "1",
      post_date: "2019-03-31 09:51:44",
      post_date_gmt: "2019-03-31 08:51:44",
      post_content:
        "Saucony, the famous athletic shoe manufacturer. More than a century old great American brand that is continued satisfying sneakerheads all over the world. In FastSole, we value this long journey, and that’s why you roll over to us for your best Saucony deal. What established in 1898, came in today’s position over the year of craftsmanship, technology and design aspect. Saucony is storming the sneaker world with their Grid, Grid SD, Shadow and Freedom line of shoes. The quality assures not only the sports people, but unique colour contrast also gains the fashion universe.",
      post_title: "",
      post_excerpt: "",
      post_status: "publish",
      comment_status: "closed",
      ping_status: "closed",
      post_password: "",
      post_name: "63781",
      to_ping: "",
      pinged: "",
      post_modified: "2019-03-31 09:51:51",
      post_modified_gmt: "2019-03-31 08:51:51",
      post_content_filtered: "",
      post_parent: 0,
      guid: "https://fastsole.co.uk/?p=63781",
      menu_order: 7,
      post_type: "nav_menu_item",
      post_mime_type: "",
      comment_count: "0",
      filter: "raw",
      db_id: 63781,
      menu_item_parent: "0",
      object_id: "76",
      object: "department",
      type: "taxonomy",
      type_label: "Department",
      url: "/sneaker-release-dates/brands/saucony/",
      title: "Saucony",
      target: "",
      attr_title: "",
      description:
        "Saucony, the famous athletic shoe manufacturer. More than a century old great American brand that is continued satisfying sneakerheads all over the world. In FastSole, we value this long journey, and that’s why you roll over to us for your best Saucony deal. What established in 1898, came in today’s position over the year of craftsmanship, technology and design aspect. Saucony is storming the sneaker world with their Grid, Grid SD, Shadow and Freedom line of shoes. The quality assures not only the sports people, but unique colour contrast also gains the fashion universe.",
      classes: [""],
      xfn: "",
      slug: "saucony",
    },
  ],
};
